resolver: lts-9.13
flags: {}
extra-package-dbs: []
packages:
- .
- location:
    git: https://github.com/ejconlon/analyze
    commit: b38eef0b735c01504980a155187517992a77f1f6
extra-deps:
- ghc-mod-5.8.0.0

